name: Build and Release Overlord

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set version from tag
        shell: pwsh
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
          Set-Content -Path src/version.py -Value "__version__ = '$tag'"
          # Update installer.iss with the version for AppVersion, VersionInfoVersion, and OutputBaseFilename
          $dashed = $tag -replace '\.', '-'
          (Get-Content installer.iss) \
            -replace 'AppVersion=__APP_VERSION__', "AppVersion=$tag" \
            | ForEach-Object { $_ -replace 'VersionInfoVersion=__APP_VERSION__', "VersionInfoVersion=$tag" } \
            | ForEach-Object { $_ -replace 'OutputBaseFilename=OverlordInstaller__APP_VERSION_DASHED__', "OutputBaseFilename=OverlordInstaller$dashed" } \
            | Set-Content installer.iss

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install Pillow
        run: pip install pillow

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build overlord.exe
        shell: pwsh
        run: ./scripts/createExecutable.ps1

      - name: Build Installer
        run: |
          iscc installer.iss
        working-directory: ${{ github.workspace }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/OverlordInstaller*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
