name: Build and Release Overlord

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install Pillow
        run: pip install pillow

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build overlord.exe
        shell: pwsh
        run: ./scripts/createExecutable.ps1

      - name: Build Installer
        run: |
          iscc installer.iss
        working-directory: ${{ github.workspace }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/overlord-setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
